import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*End of head*/}
      <main className="h-screen flex items-center justify-center">
         <form className="bg-white flex rounded lg w-1/2 font-latoRegular">
            <div className="flex text-gray-700 p-20">
               <h1>let's get started..</h1>
               <p>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt odio quam,
                quod voluptatum exercitationem nulla eligendi veritatis
                 odit magni itaque quas neque perferendis nobis consequatur?
                  Hic quod voluptate rem eaque?
                </p>
            </div>
            {/*End of div*/}
            <div>
            </div>
            {/*End of div*/}
         </form>
      </main> 
    </div>
  )
}
