import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
           <header>
               <nav>
                   <img src="" alt="" />
                    {/**/}
                    <a href="/">Home</a> 
                   <a href="./events">Events</a>
                   <a href="./about-us.js">About us</a> 
               </nav>
           </header>
               {/**/}
           <main className={styles.main}>
              <div>
                  <a href="">
                     <img src="" alt="" />
                     <h2>Events in life in earth..</h2>
                     <p>
                       Lorem ipsum dolor sit amet consectetur <br/> adipisicing elit.
                       Praesentium mollitia eum vel quos temporibus ex deleniti magni doloremque,<br/>
                       ipsum illum fugiat deserunt eaque voluptatem impedit<br/>
                       consequatur veniam nam dolore voluptates!
                     </p>
                  </a>
                  {/*End of card*/} 
                  <a href="">
                     <img src="" alt="" />
                     <h2>Events in life moon..</h2>
                     <p>
                        Lorem ipsum dolor sit amet consectetur <br/> adipisicing elit.
                        Praesentium mollitia eum vel quos temporibus ex deleniti magni doloremque,<br/>
                        ipsum illum fugiat deserunt eaque voluptatem impedit<br/>
                        consequatur veniam nam dolore voluptates!
                     </p>
               </a>
               {/*End of card*/} 
              </div>
           </main>
               {/**/}
           <footer className={styles.footer}>
               <p>
               &copy; copyright <span id="date"></span> -
               <span class="footer-logo">Events app</span> built by <a href="#">fua alfu</a>
               </p>
           </footer>
               {/**/}
    </>
  )
}
